### ISSUE TITLE
Lionbot +2/-2 highscore integration?

### ISSUE THREAD

**Issue by gleasonw** [birkholz/lionbot#12]
Hello,

I've been tinkering with a service to track +2/-2s in NL's chat. It could be fun to post the daily 10 second +2/-2 highscore clip with Lionbot. Thoughts? I could start a fork to see how doable it is. 

Here's the response for top 2 counts in the past day: https://nljokeval-production.up.railway.app/api/clip_counts?span=day&grouping=second&order=desc&column=two

And lowest 2 counts: https://nljokeval-production.up.railway.app/api/clip_counts?span=day&grouping=second&order=asc&column=two

I'm currently powering a dashboard with the same API here: https://nl-joke-val.vercel.app

**Comment by birkholz** [comment]
Sorry for the late response, I don't really check GitHub notifications much, and I haven't been working on lionbot for a while.

That's certainly an interesting project. We'd have to get approval from the discord moderators if we wanted to post anything to discord, but I could certainly see it making sense to post them to the #clips channel.

**Comment by gleasonw** [comment]
Sounds good, I'll reach out to the mods. If they're game, I'll start a lionbot PR.
